kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imageswap-write
  namespace: imageswap-system
  labels:
    app: imageswap
    resource: clusterrole
rules:
- apiGroups:
  - admissionregistration.k8s.io
  - certificates.k8s.io
  - ""
  resources:
    - mutatingwebhookconfigurations
    - certificatesigningrequests
    - certificatesigningrequests/approval
    - certificatesigningrequests/status
    - signers
  verbs:
    - get
    - list
    - watch
    - create
    - patch
    - update
    - delete
    - approve

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imageswap-read
  labels:
    app: imageswap
    resource: clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imageswap-write-crb
  labels:
    app: imageswap
    resource: clusterrolebinding
roleRef:
  kind: ClusterRole
  name: imageswap-write
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: imageswap-sa
  namespace: imageswap-system

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imageswap-read-crb
  labels:
    app: imageswap
    resource: clusterrolebinding
roleRef:
  kind: ClusterRole
  name: imageswap-read
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: imageswap-sa
  namespace: imageswap-system
